#!/bin/bash

# Right now it's only testing if the code compiles. Need to test if it runs too.

set -e

dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
srcfile="$(mktemp /tmp/callfull.XXXXXXXXXX)"
exefile="$(mktemp /tmp/callfull.XXXXXXXXXX)"

sed -n '/^```c/,/^```/ p' < "$dir/../README.md" | sed '1d;$d' > "$srcfile"

cc -o "$exefile" -I"$dir/.." "$dir/../callfull.c" -xc - < "$srcfile"

output="$("$exefile" < /dev/urandom)"

expected="Process 1/4 (16000 bytes)
Process 2/4 (16000 bytes)
Process 3/4 (16000 bytes)
Process 4/4 (16000 bytes)"

if [ "$output" != "$expected" ]; then
    echo "Unexpected output." >&2
    echo "$output"
    exit 1
fi